language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - git submodule update --init --recursive
install:
  - ./bootstrap.py
script:
  - ./manage.py test djangosherd --settings=settings_test
  - ./manage.py test assetmgr --settings=settings_test
  - ./manage.py test projects --settings=settings_test
  - ./manage.py test mediathread_main --settings=settings_test
